---
deployments:
- name: OLYMPEX-D1_2015
  platforms:
  - name: DC-8
    files:
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_20151219-2153.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_20151219-2153.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_parameters_20151219.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_20151219-0357.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_20151219-0357.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_parameters_20151219.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_parameters_20151218.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_20151218-0748.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_20151218-0748.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_parameters_20151218.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_parameters_20151213.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_20151213-1900.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_parameters_20151213.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_20151213-1900.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_parameters_20151212.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_20151212-2206.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_20151212-2206.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_parameters_20151212.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_20151210-2011.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_20151210-2011.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_parameters_20151210.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_20151210-1404.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_20151210-1404.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_parameters_20151210.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_20151208-2033.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_parameters_20151208.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_20151208-2033.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_parameters_20151208.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_parameters_20151205.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_20151205-1900.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_20151205-1900.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_parameters_20151205.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_parameters_20151204.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_20151204-1806.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_20151204-1806.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_parameters_20151204.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_parameters_20151203.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_20151203-1736.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_parameters_20151203.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_20151203-1736.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_20151202-0158.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_parameters_20151202.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_20151202-0158.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_parameters_20151202.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_parameters_20151125.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_20151125-1945.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_20151125-1945.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_parameters_20151125.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_parameters_20151124.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_20151124-2028.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_20151124-2028.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_parameters_20151124.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_20151123-2212.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_parameters_20151123.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_20151123-2212.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_20151119-0039.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_parameters_20151119.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_20151119-0039.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_parameters_20151114.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_20151114-2349.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_parameters_20151114.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_20151114-2349.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_parameters_20151113.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_20151113-2012.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_20151113-2012.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_20151112-2245.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_parameters_20151112.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_20151112-2245.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_parameters_20151110.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_20151110-2138.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_20151110-2138.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_10hz_20151105-2308.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnavdc8olyx__1/olympex_navdc8_IWG1_20151105-2308.txt
  - name: ER-2
    files:
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_parameters_20151109.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_20151109-2159.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_parameters_20151110.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_20151110-1937.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_parameters_20151117.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_20151117-0311.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_20151119-0046.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_parameters_20151119.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_20151123-2228.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_parameters_20151123.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_parameters_20151124.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_20151124-2232.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_20151202-0228.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_parameters_20151202.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_parameters_20151203.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_20151203-1749.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_parameters_20151204.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_20151204-2018.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_20151205-1812.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_parameters_20151205.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_20151209-0045.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_parameters_20151209.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_20151210-2210.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_parameters_20151210.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_parameters_20151212.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_20151212-2220.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_parameters_20151214.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_20151214-0014.txt
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_parameters_20151215.xml
    - https://data.ghrc.earthdata.nasa.gov/ghrcw-protected/gpmnaver2olyx__1/olympex_naver2_IWG1_20151215-2007.txt
