---
deployments:
- name: GloPac-D1_2010
  platforms:
  - name: GH
    tsv_format: true
    rename_as_ict: true
    coords_divisor: 1000
    files:
    - https://espoarchive.nasa.gov/archive/download/FP20100402.GH
    - https://espoarchive.nasa.gov/archive/download/FP20100407.GH
    - https://espoarchive.nasa.gov/archive/download/FP20100413.GH
    - https://espoarchive.nasa.gov/archive/download/FP20100423.GH
    - https://espoarchive.nasa.gov/archive/download/FP20100430.GH