name: Lint and Test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    working-directory: ./task

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
